version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - BOT_LANGUAGE=zh-tw
      - TELEGRAM_BOT_TOKEN=
      - ADMIN_USER_IDS=
      - ALLOWED_TELEGRAM_USER_IDS=
      - OPENAI_API_KEY=
      - OPENAI_BASE_URL=
      - OPENAI_MODEL=gpt-4o
      - ASSISTANT_PROMPT=用繁體廣東話回答
      - VISION_MODEL=gpt-4-turbo
      - IGNORE_GROUP_VISION=false
      - ENABLE_VISION=true
      - ENABLE_IMAGE_GENERATION=true
      - ENABLE_TTS_GENERATION=true
      - ENABLE_TRANSCRIPTION=true
      - ENABLE_FUNCTIONS=true
      - SHOW_PLUGINS_USED=rue
      - PLUGINS=weather,ddg_web_search,ddg_image_search,worldtimeapi,youtube_audio_extractor,web_scraping,edge_tts
      - WORLDTIME_DEFAULT_TIMEZONE=Asia/Hong_Kong
      - WOLFRAM_APP_ID=
    restart: unless-stopped
